/* TABELLE BASE */

CREATE TABLE ARTISTA (
    ID_ARTISTA INTEGER PRIMARY KEY,
    Nome TEXT NOT NULL
);

CREATE TABLE PALCO (
    ID_PALCO INTEGER PRIMARY KEY,
    Descrizione TEXT NOT NULL
);

CREATE TABLE TIPO_BIGLIETTO (
    ID_TIPO_BIGLIETTO INTEGER PRIMARY KEY,
    Descrizione TEXT NOT NULL,
    Prezzo REAL NOT NULL
);

CREATE TABLE UTENTE (
    ID_UTENTE INTEGER PRIMARY KEY,
    Password TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    Nome TEXT,
    Cognome TEXT,
    Type TEXT NOT NULL CHECK (Type IN ('PARTECIPANTE', 'ORGANIZZATORE'))
);

CREATE TABLE PERCORSO_IMMAGINE (
    percorso TEXT PRIMARY KEY,
    ID_ARTISTA INTEGER NOT NULL,
    FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTA (ID_ARTISTA)
);

CREATE TABLE PERFORMANCE (
    ID_PERFORMANCE INTEGER PRIMARY KEY,
    Giorno TEXT NOT NULL CHECK (Giorno IN ('Venerdì', 'Sabato', 'Domenica')),
    Ora TEXT NOT NULL,
    Durata INTEGER NOT NULL,
    Descrizione TEXT NOT NULL,
    Stato BOOLEAN NOT NULL DEFAULT 0,
    Genere_musicale TEXT NOT NULL,
    ID_UTENTE INTEGER NOT NULL,
    ID_ARTISTA INTEGER NOT NULL,
    ID_PALCO INTEGER NOT NULL,
    FOREIGN KEY (ID_PALCO) REFERENCES PALCO (ID_PALCO),
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE (ID_UTENTE),
    FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTA (ID_ARTISTA)
);

CREATE TABLE BIGLIETTO (
    ID_BIGLIETTO INTEGER PRIMARY KEY,
    ID_TIPO_BIGLIETTO INTEGER NOT NULL,
    giorno_riferimento TEXT CHECK (giorno_riferimento IN ('Venerdì', 'Sabato', 'Domenica')),
    FOREIGN KEY (ID_TIPO_BIGLIETTO) REFERENCES TIPO_BIGLIETTO (ID_TIPO_BIGLIETTO)
);

/* Relazione tra Utente e Biglietto*/
CREATE TABLE ACQUISTARE (
    ID_UTENTE INTEGER PRIMARY KEY,
    ID_BIGLIETTO INTEGER NOT NULL UNIQUE,
    TimeStamp_emissione TEXT NOT NULL,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE (ID_UTENTE),
    FOREIGN KEY (ID_BIGLIETTO) REFERENCES BIGLIETTO (ID_BIGLIETTO)
);